### ISSUE TITLE
using erpc vs rpc

### ISSUE THREAD

**Issue by TwistingTwists** [am-kantox/cloister#46]
https://github.com/am-kantox/cloister/blob/master/lib/cloister/node.ex#L28

https://www.erlang.org/doc/man/rpc.html
```
 The erpc implementation also provides a more scalable implementation with better performance than the original rpc implementation. However, since the introduction of erpc, the rpc module implements large parts of its central functionality using erpc, so the rpc module won't not suffer scalability wise and performance wise compared to erpc.
```
erpc
``` Enhanced in the sense that it makes it possible to distinguish between returned value, raised exceptions, and other errors.```

I am not aware, at the moment, about plans to bring exception and error handling on clusters for this library. But if so, this might be of interest.

**Comment by am-kantox** [comment]
Hi @TwistingTwists, 

thanks for the suggestion; I have plans to improve the library to use `erpc`, but at the moment it just works and I have zero spare time to dedicate to it.
